GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/3

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "new name 7",
    "number": "39-44-5323523"
}
